### PR TITLE
Improve Package Details UX

### PR DESCRIPTION
**Pull request by giggsey**
image

image

image

### CODE REVIEW

**Comment by giggsey** [comment]
I think the header should get a bit more consistent across these pages too.

"[Package name] [page]" with Package name being a link back to the Details.

Not sure about Package list being a button on each of those pages

**Review by akondas — APPROVED** [review]

**Comment by akondas** [comment]
Tested :+1:, UX feels much better, thanks @giggsey.
I like your idea with small package button on the left. You can change this as well :wink:

**Comment by giggsey** [comment]
image

image

Using JavaScript to format the numbers to allow for different locales without having to build support into the backend

**Comment by akondas** [comment]
Nice, link to stats in package details is also good UX :+1:

**Pull request merged**
