### PR TITLE
Update Symfony to 5.1

### PR DESCRIPTION
**Pull request by marmichalski**
Related to #206, #239

### CODE REVIEW

**Comment by marmichalski** [comment]
Seems there is [an issue](https://github.com/symfony/symfony/issues/37179) with 5.1. Will resolve it when I'm back at keyboard 😎

**Comment by akondas** [comment]
:thinking: recently a lot of this type of errors after updates

**Comment by karniv00l** [comment]
I couldn't push directly so I've made PR out if this #250

**Comment by akondas** [comment]
Thanks, will be merged in #250

**Pull request closed without merging**
