### PR TITLE
Make domain separators configurable

### PR DESCRIPTION
**Pull request by JeckLabs**
First of all, thanks for your amazing work.
Right now, I'm working on a helm chart to deploy the Repman in the Kubernetes cluster.
Among other things, I want to configure domain separators via environmental variables. 
So this is what this pull request for.

### CODE REVIEW

**Review by akondas — CHANGES_REQUESTED** [review]
Hi, thanks for PR. Looks ok, but you need also add changes in:
- [x] config/packages/security.yaml (firewall and access control)

**Comment by JeckLabs** [comment]
Sorry, I missed that. It should be fixed now. Thanks!

**Review by akondas — APPROVED** [review]
LGTM :+1:

**Review by karniv00l — APPROVED** [review]

**Comment by akondas** [comment]
One more, we need to make sure that this change is backward compatible. Please add to:
```
organization_separator: '%env(resolve:APP_ORGANIZATION_SEPARATOR)%'
```
default fallback for `domain_separator`. Maybe `APP_ORGANIZATION_SEPARATOR` should be commented out by default?


CC @jmalinens

**Comment by jmalinens** [comment]
> One more, we need to make sure that this change is backward compatible. Please add to:
> 
> ```
> organization_separator: '%env(resolve:APP_ORGANIZATION_SEPARATOR)%'
> ```
> 
> default fallback for `domain_separator`. Maybe `APP_ORGANIZATION_SEPARATOR` should be commented out by default?
> 
> CC @jmalinens

Maybe something like that should be enough but I don't see it as huge BC break and it can be left "as is"

```yaml
parameters:
  env(APP_ORGANIZATION_SEPARATOR): '%domain_separator%'
```

(if APP_ORGANIZATION_SEPARATOR env variable is not set up it will fall back to domain_separator param)

**Comment by akondas** [comment]
@jmalinens Ok, if this does not apply to you, I can accept it even as it is now.

**Comment by JeckLabs** [comment]
@jmalinens, I see possible issues for docker users. They use separate `.env.docker` and would not have a default value for `APP_ORGANIZATION_SEPARATOR` after an upgrade. Probably I should add smth like `%env(default:domain_separator:resolve:APP_ORGANIZATION_SEPARATOR)` in config — will test it later tonight.

**Comment by JeckLabs** [comment]
@akondas, check the latest commit, pls. It should fix compatibility issues. I checked in the docker environment.

**Review by akondas — APPROVED** [review]

**Comment by akondas** [comment]
Thanks @JeckLabs :+1:

**Comment by akondas** [comment]
I will merge tomorrow (if that's not a problem), today i have a day off :wink:

**Pull request merged**
