### PR TITLE
Add repman:create:user command

### PR DESCRIPTION
**Pull request by nickygerritsen**
Part of #159

### CODE REVIEW

**Comment by akondas** [comment]
It seems to me that we can safely add another command, a slight duplication here will not hurt and there will be a better separation of the concept.

**Comment by nickygerritsen** [comment]
OK done 😄

**Comment by akondas** [comment]
Well done, rebase please and we can merge this :+1:

**Comment by nickygerritsen** [comment]
Done :)

**Comment by akondas** [comment]
Thanks :+1:

**Pull request merged**
